config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true, length: { maximum: 50 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  has_many :book_comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end


  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end  
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
   if @book.update(book_params)
     flash[:notice]="Book was successfully updated."
     redirect_to book_path(@book.id)
   else
     render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with model: book, local:true do |f| %>
  <label for="book_title">Title</label>
  <%= f.text_field :title, class: "form-control" %>
  
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class: "form-control"  %>

  <div class="actions">
    <%= f.submit 'Create Book', class: "btn  btn-block btn-success mt-4" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= form_with model:@book, local: true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title, class:"form-control" %>
        <h4>Opinion</h4>
        <%= f.text_area :body, class:"form-control" %>

        <%= f.submit 'Update Book', class:"btn btn-lg btn-block btn-info mt-4" %>

        <div class="select-box">
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table book-index">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if current_user.already_favorited?(@book) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
                <%= @book.favorites.count %>
              </td>
              <td>コメント数：<%= @book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table book-show">
        <tr>
          <td>
            <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br />
            <%= link_to @user.name, user_path(@user) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td>
            <% if current_user.already_favorited?(@book) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="far fa-heart"></i>
              <% end %>
            <% end %>
            <%= @book.favorites.count %>
          </td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <table class="table book_comment">
        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br />
              <%= book_comment.user.name %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
              <td>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: " btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>

      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <div class="row" >
          <%= f.text_area :comment, class: "col-md-11 comment_content" %><br >
        </div>
        <div class="actions">
          <%= f.submit '送信', class: "btn btn-outline-dark mt-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6" >
      <h1>welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions, impressions, and emotions</p>
      <p>about various books!</p> 
      <div class="btn-wrapper col-10 mx-auto" >
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-block mb-3 sign_in" %>
	      </div>
	      <div class="row">
	       <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-block mb-3 sign_up" %>
	      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user) do %>
                  <i class="fas fa-home nav-link text-light"> Home </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path do %>
                  <i class="fas fa-users nav-link text-light"> Users </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path do %>
                  <i class="fas fa-book-open nav-link text-light"> Books </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt nav-link text-light"> logout </i>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path do %>
                  <i class="fas fa-home nav-link text-light"> Home </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path do %>
                  <i class="fas fa-link nav-link text-light"> About </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path do %>
                  <i class="fas fa-user-plus nav-link text-light"> sign up </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path do %>
                  <i class="fas fa-sign-in-alt nav-link text-light"> login </i>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>  
        </div>
      </nav>
    </header>

    <div class="main">
      <p class="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h4><%= model.errors.count %> errors prohibited this obj from being saved:</h4>
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<table class="table user">
  <h2>User info</h2>
  <thead>
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th colspan="2">
        <%= link_to "", edit_user_path(user), {class:"btn btn-outline-secondary btn-block fas fa-user-cog"} %>
      </th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User Info</h2>
      <%= render 'users/error', model: @user %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="user-name">Name</div>
          <%= f.text_field :name %>
        <div class="user-edit-image">Image</div>
          <%= f.attachment_field :profile_image %>
        <div class="form-body">Introduction</div>
          <%= f.text_area :introduction %><br />
        <div class="btn btn-secondary">
          <%= f.submit "Update User" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table user-index">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", "/users/#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>
     </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table users-books">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fil, 30, 30, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= link_to book.body %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>